export const PUBLIC_FOLDER = "./public";
export const BUILD_FOLDER = "./dist";

const POPUP_PATH = "index.html";
const POPUP_SCRIPT_RESOLVE_NAME = "popup";

const ARM_METROLOG_SCRIPT_PATH =
  "src/content_script/contentARMmetrolog/contentARMmetrolog.ts";
const ARM_METROLOG_SCRIPT_RESOLVE_NAME = "contentARMmetrolog";

const FUND_METROLOGY_SCRIPT_PATH =
  "src/content_script/contentFundMetrology/contentFundMetrology.ts";
const FUND_METROLOGY_SCRIPT_RESOLVE_NAME = "contentFundMetrology";

const ROSACCREDITATION_SCRIPT_PATH =
  "src/content_script/contentRosaccreditation/contentRosaccreditation.ts";
const ROSACCREDITATION_SCRIPT_RESOLVE_NAME = "contentRosaccreditation";

const SERVICE_WORKER_SCRIPT_PATH = "src/service_worker/service_worker.ts";
const SERVICE_WORKER_SCRIPT_RESOLVE_NAME = "service";

const FUND_METROLOGY_PERSONAL_SCRIPT_PATH =
  "src/content_script/contentFundMetrologyPersonal/contentFundMetrologyPersonal.ts";
const FUND_METROLOGY_PERSONAL_SCRIPT_RESOLVE_NAME =
  "contentFundMetrologyPersonal";

export const ALL_FILES_STRING = `${ARM_METROLOG_SCRIPT_PATH} ${FUND_METROLOGY_SCRIPT_PATH} ${ROSACCREDITATION_SCRIPT_PATH} ${SERVICE_WORKER_SCRIPT_PATH} ${POPUP_PATH} ${FUND_METROLOGY_PERSONAL_SCRIPT_PATH}`;

export const FILES_ALIASES = {
  [POPUP_SCRIPT_RESOLVE_NAME]: POPUP_PATH,
  [ARM_METROLOG_SCRIPT_RESOLVE_NAME]: ARM_METROLOG_SCRIPT_PATH,
  [FUND_METROLOGY_SCRIPT_RESOLVE_NAME]: FUND_METROLOGY_SCRIPT_PATH,
  [ROSACCREDITATION_SCRIPT_RESOLVE_NAME]: ROSACCREDITATION_SCRIPT_PATH,
  [SERVICE_WORKER_SCRIPT_RESOLVE_NAME]: SERVICE_WORKER_SCRIPT_PATH,
  [FUND_METROLOGY_PERSONAL_SCRIPT_RESOLVE_NAME]:
    FUND_METROLOGY_PERSONAL_SCRIPT_PATH,
};
