import { Api } from "@common/api/api.class";
import {
  CONTENT_SCRIPT_LISTENERS_TYPES,
  CONTENT_SCRIPT_SENDERS_TYPES,
  POPUP_SCRIPT_LISTENERS_TYPES,
  POPUP_SCRIPT_SENDERS_TYPES,
} from "@common/api/types/messagesTypes";

export const serviceWorkerApi = new Api<
  CONTENT_SCRIPT_LISTENERS_TYPES | POPUP_SCRIPT_LISTENERS_TYPES,
  CONTENT_SCRIPT_SENDERS_TYPES | POPUP_SCRIPT_SENDERS_TYPES
>();
