const DATA_RECEIVED = "DATA_RECEIVED";
const PAGE_FUNDMETROLOGY_CLOSE = "PAGE_FUNDMETROLOGY_CLOSE";
const CONTENT_FUNDMETROLOGY_SCRIPT_READY = "CONTENT_FUNDMETROLOGY_SCRIPT_READY";
const ERR_NOT_LOADED_DATA = "ERR_NOT_LOADED_DATA";
const ERR_UNKNOWN = "ERR_UNKNOWN";
const DATA_FUNDMETROLOGY = "DATA_FUNDMETROLOGY";
const PAGE_READY_FOR_DATA_ENTERED = "PAGE_READY_FOR_DATA_ENTERED";
const CONTENT_ROSACCREDITATION_SCRIPT_READY =
    "CONTENT_ROSACCREDITATION_SCRIPT_READY";
const CONTENT_ARMMETROLOG_SCRIPT_READY = "CONTENT_ARMMETROLOG_SCRIPT_READY";
const PAGE_ARMMETRLOG_CLOSE = "PAGE_ARMMETRLOG_CLOSE";
const PAGE_ROSACCREDITATION_CLOSE = "PAGE_ROSACCREDITATION_CLOSE";
const GET_DATA = "GET_DATA";
const GET_DATA_COUNT = "GET_COUNT";
const DATA_ARMMETROLOG_ENTERED = "DATA_ARMMETROLOG_ENTERED";
const DATA_ROSACCREDITATION_ENTERED = "DATA_ROSACCREDITATION_ENTERED";
const BG_SYNC_ROSACCREDITATION = "BG_SYNC_ROSACCREDITATION";
const BG_SYNC_ARMMETROLOG = "SYNC_LOCA";
const POPUP_UPDATE_DATA_STATUS = "POPUP_UPDATE_DATA_STATUS";
const BG_GET_DATA = "BG_GET_DATA";

const NULL = "NULL";
const READY = "READY";

export {
    DATA_RECEIVED,
    PAGE_FUNDMETROLOGY_CLOSE,
    CONTENT_FUNDMETROLOGY_SCRIPT_READY,
    ERR_NOT_LOADED_DATA,
    ERR_UNKNOWN,
    DATA_FUNDMETROLOGY,
    PAGE_READY_FOR_DATA_ENTERED,
    CONTENT_ROSACCREDITATION_SCRIPT_READY,
    PAGE_ROSACCREDITATION_CLOSE,
    GET_DATA,
    GET_DATA_COUNT,
    NULL,
    READY,
    DATA_ROSACCREDITATION_ENTERED,
    BG_SYNC_ARMMETROLOG,
    BG_SYNC_ROSACCREDITATION,
    POPUP_UPDATE_DATA_STATUS,
    BG_GET_DATA,
    CONTENT_ARMMETROLOG_SCRIPT_READY,
    PAGE_ARMMETRLOG_CLOSE,
    DATA_ARMMETROLOG_ENTERED,
};
