const KEY_CONTENT_FUNDMETROLOGY_STATUS = "CONTENT_FUNDMETROLOGY_STATUS";
const KEY_CONTENT_ROSACCREDITATION_STATUS = "CONTENT_ROSACCREDITATION_STATUS";
const KEY_CONTENT_ARMMETROLOG_STATUS = "CONTENT_ARMMETROLOG_STATUS";
const KEY_DATA_FOR_ROSACCREDITATION = "DATA_ROSACCREDITATION";
const KEY_DATA_FOR_ARMMETROLOG = "DATA_ARMMETROLOG";
const KEY_CURRENT_NUMBER_OF_TABLE = "CURRENT_NUMBER_OF_TABLE";
const KEY_COUNT_OF_ROWS = "COUNT_OF_ROWS";
const KEY_COUT_DATA_TO_SYNC_ROSACCREDITATION =
    "COUT_DATA_TO_SYNC_ROSACCREDITATION";
const KEY_COUT_DATA_TO_SYNC_ARMMETROLOG = "COUT_DATA_TO_SYNC_ARMMETROLOG";

const LAST_NAME = "last_name";
const FIRST_NAME = "first_name";
const MIDDLE_NAME = "middle_name";
const USER_EMAIL = "email";
const KEY_USER_DATA = "USER_DATA";

// MEASURING_INSTRUMENT = MI
const REGISTRATION_NUMBER_OF_MI = "registration_number_of_mi";
const TYPE_OF_MI = "type_of_mi";
const DATE_OF_VERIFICATION = "date_of_verification";
const VERIFICATION_NUMBER = "verification_number";
const NAME_OF_MI = "name_of_mi";
const MODIFICATION_OF_MI = "modification_of_mi";
const VALID_UNTIL = "valid_until";

export {
    KEY_CONTENT_FUNDMETROLOGY_STATUS,
    KEY_CONTENT_ROSACCREDITATION_STATUS,
    KEY_DATA_FOR_ROSACCREDITATION,
    KEY_CURRENT_NUMBER_OF_TABLE,
    KEY_COUNT_OF_ROWS,
    LAST_NAME,
    FIRST_NAME,
    MIDDLE_NAME,
    USER_EMAIL,
    REGISTRATION_NUMBER_OF_MI,
    TYPE_OF_MI,
    DATE_OF_VERIFICATION,
    VERIFICATION_NUMBER,
    KEY_CONTENT_ARMMETROLOG_STATUS,
    KEY_DATA_FOR_ARMMETROLOG,
    KEY_COUT_DATA_TO_SYNC_ROSACCREDITATION,
    KEY_COUT_DATA_TO_SYNC_ARMMETROLOG,
    KEY_USER_DATA,
    NAME_OF_MI,
    MODIFICATION_OF_MI,
    VALID_UNTIL,
};
